#! /bin/sh

export EP_ENGINE_VERSION="c4ede32c575a231e71d82f5fee71887e14ef22b5"

CWD="`pwd`"
D0="`dirname "$0"`"
cd "$D0/../lib/python"
root="`pwd`"
cd "$CWD"

if test -z "$PYTHONPATH"; then
   PYTHONPATH="$root"
else
   PYTHONPATH="$root:$PYTHONPATH"
fi
export PYTHONPATH
exec "$root"/`basename "$0"` "$@"
