{
 "title": "Completed Requests",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{type=\"completed-request\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "{cluster=~\"$cluster\", type=\"completed-request\"}"
   },
   {
    "name": "statement",
    "label": "Statement",
    "query": "{cluster=~\"$cluster\", type=\"completed-request\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Completed Requests - Queue Time(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max without(query_request_id)(query_completed_request_queue_time_ms{cluster=~\"$cluster\", node=~\"$node\", type=\"completed-request\", statement=~\"$statement\", job!=\"Cluster1\"})",
     "legendFormat": "{{cluster}} - {{node}} - {{statement}}"
    }
   ]
  },
  {
   "title": "Completed Requests - Elapsed Time(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max without(query_request_id)(query_completed_request_elapsed_time_ms{cluster=~\"$cluster\", node=~\"$node\", type=\"completed-request\", statement=~\"$statement\", job!=\"Cluster1\"})",
     "legendFormat": "{{cluster}} - {{node}} - {{statement}}"
    }
   ]
  },
  {
   "title": "Completed Requests - Result Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max without(query_request_id)(query_completed_request_result_count{cluster=~\"$cluster\", node=~\"$node\", type=\"completed-request\", statement=~\"$statement\", job!=\"Cluster1\"})",
     "legendFormat": "{{cluster}} - {{node}} - {{statement}}"
    }
   ]
  },
  {
   "title": "Completed Requests - Result Size Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max without(query_request_id)(query_completed_request_result_size_bytes{cluster=~\"$cluster\", node=~\"$node\", type=\"completed-request\", statement=~\"$statement\", job!=\"Cluster1\"})",
     "legendFormat": "{{cluster}} - {{node}} - {{statement}}"
    }
   ]
  },
  {
   "title": "Completed Requests - Query Selectivity %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max without(query_request_id)(query_completed_request_query_selectivity_percent{cluster=~\"$cluster\", node=~\"$node\", type=\"completed-request\", statement=~\"$statement\", job!=\"Cluster1\"})",
     "legendFormat": "{{cluster}} - {{node}} - {{statement}}"
    }
   ]
  },
  {
   "title": "Completed Requests - Scan Results",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max without(query_request_id)(query_completed_request_scan_results{cluster=~\"$cluster\", node=~\"$node\", type=\"completed-request\", statement=~\"$statement\", job!=\"Cluster1\"})",
     "legendFormat": "{{cluster}} - {{node}} - {{statement}}"
    }
   ]
  },
  {
   "title": "Completed Requests - Fetches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max without(query_request_id)(query_completed_request_fetches{cluster=~\"$cluster\", node=~\"$node\", type=\"completed-request\", statement=~\"$statement\", job!=\"$cluster\"})",
     "legendFormat": "{{cluster}} - {{node}} - {{statement}}"
    }
   ]
  }
 ]
}