{
 "title": "couchbase-performance-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "{type=\"bucket\"}"
   },
   {
    "name": "node",
    "query": "{type=\"bucket\", cluster=~\"$cluster\"}"
   },
   {
    "name": "bucket",
    "query": "{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\"}"
   },
   {
    "name": "node_index",
    "query": "{type=\"index\", cluster=~\"$cluster\"}"
   },
   {
    "name": "index",
    "query": "{type=\"index\", cluster=~\"$cluster\", node=~\"$node_index\"}"
   },
   {
    "name": "query",
    "label": "query",
    "query": "{type=\"query\", cluster=~\"$cluster\"}"
   },
   {
    "name": "xdcr",
    "label": "xdcr",
    "query": "{type=\"xdcr\", cluster=~\"$cluster\"}"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status $node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "repeat": "node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "status{node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Bucket Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "sets per sec",
   "type": "graph",
   "description": "Number of writes (set operations) per second to this bucket (measured from cmd_set)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cmd_set{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "gets per sec",
   "type": "graph",
   "description": "Number of reads (get operations) per second from this bucket (measured from cmd_get)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cmd_get{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "cache_miss_ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_cache_miss_rate{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "curr_connections",
   "type": "graph",
   "description": "Number of connections to this server including \" \"connections from external client SDKs, proxies, \" \"DCP requests and internal statistic gathering",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(curr_connections{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "curr_items",
   "type": "graph",
   "description": "Number of unique items in this bucket - only active items, not replica",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(curr_items{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total Disk Size",
   "type": "graph",
   "description": "The total size on disk of all data and view files for this bucket",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(couch_total_disk_size{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "Memory used as measured from mem_used (in GB)",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mem_used{bucket=~\"$bucket\", node=~\"$node\"}/1024/1024/1024) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "disk_write_queue",
   "type": "graph",
   "description": "Number of items waiting to be written to disk in this bucket",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(disk_write_queue{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CAS ops per sec",
   "type": "graph",
   "description": "Number of operations with a CAS id per second for this bucket (measured from cas_hits)",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cas_hits{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "cpu_utilization_rate",
   "type": "graph",
   "description": "Percentage of CPU in use across all available cores on this server",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cpu_utilization_rate{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "disk creates per sec.",
   "type": "graph",
   "description": "Number of new items created on disk per second for this bucket \"\n                                       \"(measured from vb_active_ops_create + vb_replica_ops_create \"\n                                       \"+ vb_pending_ops_create",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_ops_create{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "disk write failures",
   "type": "graph",
   "description": "Number of disk read failures (measured from ep_data_read_failed)",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_data_write_failed{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "index data size",
   "type": "graph",
   "description": "Actual data size consumed by the index",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cmd_set{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "N1QL queries/sec",
   "type": "graph",
   "description": "Number of N1QL requests processed per second",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(query_requests{node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "ep_bg_fetched",
   "type": "graph",
   "description": "Number of reads per second from disk for this bucket (measured from ep_bg_fetched)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_bg_fetched{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "temp OOM per sec",
   "type": "graph",
   "description": "Number of back-offs sent per second to client SDKs due to \"  \"\\\"out of memory\\\" situations from this bucket (measured from ep_tmp_oom_errors)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_tmp_oom_errors{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "vb_active_resident_items_ratio",
   "type": "graph",
   "description": "Percentage of active items cached in RAM in this bucket (measured from  \"vb_active_resident_items_ratio)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vb_active_resident_items_ratio{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "disk read failures",
   "type": "graph",
   "description": "Number of disk read failures (measured from ep_data_read_failed)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_data_read_failed{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "vb_replica_resident_items_ratio",
   "type": "graph",
   "description": "Percentage of replica items cached in RAM in this bucket",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vb_replica_resident_items_ratio{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "ep_dcp_replica_items_remaining",
   "type": "graph",
   "description": "Number of items remaining to be sent to consumer in this bucket",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_dcp_replica_items_remaining{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "ep_oom_errors",
   "type": "graph",
   "description": "Out of Memory errors",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_oom_errors{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "docs fragmentation %",
   "type": "graph",
   "description": "How much fragmented data there is to be compacted compared to real data for the data files in this bucket",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(couch_docs_fragmentation{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "ep_item_commit_failed",
   "type": "graph",
   "description": "Items commit Failed",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_item_commit_failed{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "metadata in RAM",
   "type": "graph",
   "description": "Total amount of item  metadata consuming RAM in this bucket. Measured from ep_meta_data_memory",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_meta_data_memory{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "no of updates",
   "type": "graph",
   "description": "ep_ops_update - Number of items updated on disk per second for this bucket. Measured from vb_active_ops_update + vb_replica_ops_update \" \"+ vb_pending_ops_update",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_ops_update{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "delete_hits",
   "type": "graph",
   "description": "Number of delete operations per second for data that this bucket. Contains (measured from delete_hits)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delete_hits{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "avg_disk_update_time",
   "type": "graph",
   "description": "Average disk update time in microseconds as from disk_update histogram of timings",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_disk_update_time{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "ep_queue_size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_queue_size{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "ep_diskqueue_drain",
   "type": "graph",
   "description": "Total number of items per second being written to disk in this bucket",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_diskqueue_drain{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "ep_diskqueue_fill",
   "type": "graph",
   "description": "Total number of items per second being put on the disk queue in this",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_diskqueue_fill{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "total mutations remaining",
   "type": "graph",
   "description": "Number of documents pending to be indexed",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_docs_pending_queued{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "drain rate items/sec",
   "type": "graph",
   "description": "Number of documents indexed by the indexer per second",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_docs_indexed{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "total indexed items",
   "type": "graph",
   "description": "Current total indexed document count",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "items_count{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "index cache miss ratio",
   "type": "graph",
   "description": "Percentage of accesses to this index data\"\n                                    \"from disk as opposed to RAM (measured from\"\n                                    \"cache_misses * 100 / (cache_misses +\"\n                                    \"cache_hits))",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cache_miss_ratio{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Percentage of index data resident in memory",
   "type": "graph",
   "description": "Percentage of index data resident in memory",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "index_resident_percent{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Total memory consumed by the index storage",
   "type": "graph",
   "description": "Total memory consumed by the index storage",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memory_used{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "items scanned/sec",
   "type": "graph",
   "description": "Number of index items scanned by the indexer per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_rows_returned{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "avg_scan_latency",
   "type": "graph",
   "description": "Index  - Avg time to serve a scan request",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_scan_latency{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "index_frag_percent",
   "type": "graph",
   "description": "percentage fragmentation of the index",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "index_frag_percent{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 } },
  {
   "title": "Queries > 500ms",
   "type": "graph",
   "description": "Number of queries that take longer than 500 ms per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "query_requests_500ms{node=~\"$query\", cluster=~\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "query_requests_1000ms",
   "type": "graph",
   "description": "Number of queries that take longer than 1000 ms per second",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "query_requests_1000ms{node=~\"$query\", cluster=~\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "query_requests_5000ms",
   "type": "graph",
   "description": "Number of queries that take longer than 5000 ms per second",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "query_requests_5000ms{node=~\"$query\", cluster=~\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "request time (sec)",
   "type": "graph",
   "description": "Average end-to-end time to process a query (in seconds)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "query_avg_req_time{node=~\"$query\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "service time(sec)",
   "type": "graph",
   "description": "Average time to execute a query (in seconds)",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "query_avg_svc_time{node=~\"$query\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Outbound XDCR Operations to bucket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 }
  },
  {
   "title": "Mutations",
   "type": "graph",
   "description": "Number of mutations to be replicated to the remote cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(changes_left{type=\"xdcr\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Incoming XDCR Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 174 } },
  {
   "title": "Mutations",
   "type": "graph",
   "description": "Number of mutations to be replicated to the remote cluster",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 175 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(changes_left{type=\"xdcr\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory % Util by Couchbase Services",
   "type": "graph",
   "description": "Memory Utilization by Couchbase services. An output of TOP command",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 175 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg by (groupname) (irate(namedprocess_namegroup_memory_bytes[1m])) * 100)",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}