{
 "title": "Couchbase DCP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{type=\"bucket\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "{type=\"bucket\", cluster=\"$cluster\"}"
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\"}"
   }
  ]
 },
 "panels": [
  { "title": "2i", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ep_dcp_2i_backoff",
   "type": "graph",
   "description": "Number of backoffs for index DCP connections\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Backoffs" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_2i_backoff{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_dcp_2i_count",
   "type": "graph",
   "description": "Number of internal secondary index DCP connections in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_2i_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_dcp_2i_items_remaining",
   "type": "graph",
   "description": "Number of secondary index items remaining to be sent to consumer in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_2i_items_remaining{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_dcp_2i_items_sent",
   "type": "graph",
   "description": "Number of secondary index items per second being sent for a producer for this bucket",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_2i_items_sent{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_dcp_2i_producer_count",
   "type": "graph",
   "description": "Number of secondary index senders for this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Producers" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_2i_producer_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_dcp_2i_total_backlog_size",
   "type": "graph",
   "description": "Total size in bytes of the DCP backlog for secondary indexes\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_2i_total_backlog_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_dcp_2i_total_bytes\t",
   "type": "graph",
   "description": "Number of bytes per second being sent for secondary indexes DCP connections\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_2i_total_bytes{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Analytics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "ep_dcp_cbas_backoff\t",
     "type": "graph",
     "description": "Number of backoffs for Analytics DCP connections\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Backoffs" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_cbas_backoff{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_cbas_count\t",
     "type": "graph",
     "description": "Number of internal Analytics DCP connections in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_cbas_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_cbas_items_remaining",
     "type": "graph",
     "description": "Number of Analytics items remaining to be sent to consumer in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_cbas_items_remaining{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_cbas_items_sent",
     "type": "graph",
     "description": "Number of Analytics items per second being sent for a producer for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_cbas_items_sent{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_cbas_producer_count",
     "type": "graph",
     "description": "Number of Analytics senders for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Producers" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_cbas_producer_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_cbas_total_backlog_size",
     "type": "graph",
     "description": "Total size in bytes of the DCP backlog for analytics\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_cbas_total_backlog_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_cbas_total_bytes",
     "type": "graph",
     "description": "Number of bytes per second being sent for Analytics DCP connections\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_cbas_total_bytes{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "ep_dcp_fts_backoff",
     "type": "graph",
     "description": "Number of backoffs for FTS DCP connections\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "Backoffs" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_fts_backoff{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_fts_count",
     "type": "graph",
     "description": "Number of internal FTS DCP connections in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_fts_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_fts_items_remaining",
     "type": "graph",
     "description": "Number of FTS items remaining to be sent to consumer in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_fts_items_remaining{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_fts_items_sent",
     "type": "graph",
     "description": "Number of FTS items per second being sent for a producer for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_fts_items_sent{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_fts_producer_count",
     "type": "graph",
     "description": "Number of FTS senders for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "Producers" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_fts_producer_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_fts_total_backlog_size",
     "type": "graph",
     "description": "Total size in bytes of the DCP backlog for FTS\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_fts_total_backlog_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_fts_total_bytes",
     "type": "graph",
     "description": "Number of bytes per second being sent for FTS DCP connections",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_fts_total_bytes{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "ep_dcp_other_backoff",
     "type": "graph",
     "description": "Number of backoffs for other DCP connections\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Backoffs" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_other_backoff{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_other_count",
     "type": "graph",
     "description": "Number of other DCP connections in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_other_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_other_items_remaining",
     "type": "graph",
     "description": "Number of items remaining to be sent to consumer in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_other_items_remaining{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_other_items_sent",
     "type": "graph",
     "description": "Number of items per second being sent for a producer for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_other_items_sent{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_other_producer_count",
     "type": "graph",
     "description": "Number of other senders for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Producers" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_other_producer_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_other_total_backlog_size",
     "type": "graph",
     "description": "Total size in bytes of the DCP backlog for analytics other\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_other_total_backlog_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_other_total_bytes",
     "type": "graph",
     "description": "Number of bytes per second being sent for other DCP connections for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_other_total_bytes{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replica",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "ep_dcp_replica_backoff",
     "type": "graph",
     "description": "Number of backoffs for replication DCP connections\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Backoffs" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_replica_backoff{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_replica_count",
     "type": "graph",
     "description": "Number of internal replication DCP connections in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_replica_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_replica_items_remaining",
     "type": "graph",
     "description": "Number of replication items remaining to be sent to consumer in this bucket",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_replica_items_remaining{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_replica_items_sent",
     "type": "graph",
     "description": "Number of replication items per second being sent for a producer for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_replica_items_sent{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_replica_producer_count",
     "type": "graph",
     "description": "Number of replication senders for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "Producers" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_replica_producer_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_replica_total_backlog_size",
     "type": "graph",
     "description": "Total size in bytes of the DCP backlog for replication\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_replica_total_backlog_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_replica_total_bytes",
     "type": "graph",
     "description": "Number of bytes per second being sent for replication DCP connections\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_replica_total_bytes{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Views+Indexes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "ep_dcp_views+indexes_backoff",
     "type": "graph",
     "description": "Number of backoffs for view/index DCP connections\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Backoffs" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_indexes_backoff{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_views+indexes_count",
     "type": "graph",
     "description": "Number of internal view/index DCP connections in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_indexes_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_views+indexes_items_remaining\t",
     "type": "graph",
     "description": "Number of view/index items remaining to be sent to consumer in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_indexes_items_remaining{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_views+indexes_items_sent\t",
     "type": "graph",
     "description": "Number of view/index items per second being sent for a producer for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_indexes_items_sent{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_views+indexes_producer_count\t",
     "type": "graph",
     "description": "Number of views/index senders for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "Producers" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_indexes_producer_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_views+indexes_total_backlog_size\t",
     "type": "graph",
     "description": "Total size in bytes of the DCP backlog for views/indexes\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_indexes_total_backlog_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_views+indexes_total_bytes\t",
     "type": "graph",
     "description": "Number of bytes per second being sent for views/indexes DCP connections\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_indexes_total_bytes{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Views",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "ep_dcp_views_backoff",
     "type": "graph",
     "description": "Number of backoffs for view DCP connections\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Backoffs" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_backoff{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_views_count",
     "type": "graph",
     "description": "Number of internal view DCP connections in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_views_items_remaining",
     "type": "graph",
     "description": "Number of view items remaining to be sent to consumer in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_items_remaining{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_views_items_sent",
     "type": "graph",
     "description": "Number of view items per second being sent for a producer for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_items_sent{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_views_producer_count\t",
     "type": "graph",
     "description": "Number of view senders for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Producers" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_producer_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_views_total_backlog_size\t\t",
     "type": "graph",
     "description": "Total size in bytes of the DCP backlog for views\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_total_backlog_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_dcp_views_total_bytes",
     "type": "graph",
     "description": "Number of bytes per second being sent for view DCP connections\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_dcp_views_total_bytes{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  { "title": "XDCR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "ep_dcp_xdcr_backoff",
   "type": "graph",
   "description": "Number of backoffs for XDCR DCP connections\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Backoffs" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_xdcr_backoff{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_dcp_xdcr_count",
   "type": "graph",
   "description": "Number of internal XDCR DCP connections in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_xdcr_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_dcp_xdcr_items_remaining",
   "type": "graph",
   "description": "Number of XDCR items remaining to be sent to consumer in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_xdcr_items_remaining{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_dcp_xdcr_items_sent",
   "type": "graph",
   "description": "Number of XDCR items per second being sent for a producer for this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_xdcr_items_sent{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_dcp_xdcr_producer_count",
   "type": "graph",
   "description": "Number of XDCR senders for this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Producers" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_xdcr_producer_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_dcp_xdcr_total_backlog_size",
   "type": "graph",
   "description": "Total size in bytes of the DCP backlog for XDCR\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_xdcr_total_backlog_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_dcp_xdcr_total_bytes",
   "type": "graph",
   "description": "Number of bytes per second being sent for XDCR DCP connections\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_dcp_xdcr_total_bytes{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}