{
 "title": "Couchbase XDCR",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{type=\"xdcr\"}"
   },
   {
    "name": "replication",
    "label": "Replication",
    "query": "{type=\"xdcr\", cluster=~\"$cluster\"}"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "percent_completeness",
   "type": "graph",
   "description": "Percentage of checked items out of all checked and to-be-replicated items\n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(xdcr_percent_completeness{type=\"xdcr\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "xdc_ops",
   "type": "graph",
   "description": "Incoming XDCR operations per second for this bucket",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(data_xdc_ops{type=\"bucket\", cluster=~\"$cluster\"})",
     "legendFormat": "ops"
    }
   ]
  },
  {
   "title": "changes_left",
   "type": "graph",
   "description": "Number of mutations to be replicated to the remote cluster\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(xdcr_changes_left{type=\"xdcr\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "bandwidth_usage",
   "type": "graph",
   "description": "Bandwidth used during replication, measured in bytes per second.\n",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(xdcr_bandwidth_usage{type=\"xdcr\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "$replication Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "repeat": "replication",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(xdcr_status{type=\"xdcr\",replication=~\"$replication\"})",
     "legendFormat": "{{replication}}"
    }
   ]
  },
  {
   "title": "XDCR Replication: $replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "replication",
   "collapsed": true,
   "panels": [
    {
     "title": "xdcr_status",
     "type": "stat",
     "description": "The status of the replication",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(xdcr_status{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})"
      }
     ]
    },
    {
     "title": "percent_completeness",
     "type": "stat",
     "description": "Percentage of checked items out of all checked and to-be-replicated items\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(xdcr_percent_completeness{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "completeness"
      }
     ]
    },
    {
     "title": "data_replicated",
     "type": "graph",
     "description": "Size of data replicated in bytes\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_data_replicated{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "dcp_datach_length",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_dcp_datach_length{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "length"
      }
     ]
    },
    {
     "title": "bandwidth_usage",
     "type": "graph",
     "description": "Bandwidth used during replication, measured in bytes per second.\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_bandwidth_usage{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "bandwidth"
      }
     ]
    },
    {
     "title": "changes_left",
     "type": "graph",
     "description": "Number of mutations to be replicated to the remote cluster\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_changes_left{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "changes"
      }
     ]
    },
    {
     "title": "deletion_docs_written",
     "type": "graph",
     "description": "The number of docs deleted that have been written to the target cluster\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_deletion_docs_written{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "docs_checked",
     "type": "graph",
     "description": "Number of documents checked for changes\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_docs_checked{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "deletion_failed_cr_source",
     "type": "graph",
     "description": "The number of deletes that have failed conflict resolution on the source due to optimistic replication\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_deletion_failed_cr_source{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "dcp_dispatch_time",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_dcp_dispatch_time{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "time"
      }
     ]
    },
    {
     "title": "docs_failed_cr_source",
     "type": "graph",
     "description": "The number of docs that have failed conflict resolution on the source due to optimistic replication\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_docs_failed_cr_source{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "docs_filtered",
     "type": "graph",
     "description": "Number of documents that have been filtered out and not replicated to target cluster\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_docs_filtered{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "deletion_filtered",
     "type": "graph",
     "description": "The number of deletes that have been filtered\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_deletion_filtered{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "deletion_received_from_dcp",
     "type": "graph",
     "description": "The number of deletes that have been received from DCP\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_deletion_received_from_dcp{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "docs_received_from_dcp",
     "type": "graph",
     "description": "Number of documents received from DCP\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(xdcr_docs_received_from_dcp{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "docs_rep_queue",
     "type": "graph",
     "description": "Number of documents in replication queue\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_docs_rep_queue{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "docs_opt_repd",
     "type": "graph",
     "description": "Number of documents sent optimistically\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_docs_opt_repd{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "docs_processed",
     "type": "graph",
     "description": "The number of documents processed\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(xdcr_docs_processed{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "expiry_failed_cr_source",
     "type": "graph",
     "description": "The number of expiries that have failed conflict resolution on the source due to optimistic replication\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_expiry_failed_cr_source{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "expiry_received_from_dcp",
     "type": "graph",
     "description": "The number of expiry documents that have been received\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_expiry_received_from_dcp{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "docs_written",
     "type": "graph",
     "description": "Number of documents written to the target cluster\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_docs_written{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "expiry_docs_written",
     "type": "graph",
     "description": "The number of expiry documents written to the target cluster\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_expiry_docs_written{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "rate_replicated",
     "type": "graph",
     "description": "Rate of documents being replicated, measured in documents per second\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_rate_replicated{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "rate_doc_checks",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_rate_doc_checks{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "num_checkpoints",
     "type": "graph",
     "description": "Number of checkpoints issued in replication queue\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_num_checkpoints{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "checkpoints"
      }
     ]
    },
    {
     "title": "num_failedckpts",
     "type": "graph",
     "description": "Number of checkpoints failed during replication\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_num_failedckpts{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "checkpoints"
      }
     ]
    },
    {
     "title": "set_filtered",
     "type": "graph",
     "description": "Number of sets that have been filtered out and not replicated to target cluster\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_set_filtered{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "resp_wait_time",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 33 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_resp_wait_time{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "wait time"
      }
     ]
    },
    {
     "title": "rate_doc_opt_repd",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_rate_doc_opt_repd{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "rate_received_from_dcp",
     "type": "graph",
     "description": "Number of documents received from DCP per second\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_rate_received_from_dcp{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "time_committing",
     "type": "graph",
     "description": "Seconds elapsed during replication\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(xdcr_time_committing{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "set_received_from_dcp",
     "type": "graph",
     "description": "The number of sets that have been received from DCP\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_set_received_from_dcp{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "set_docs_written",
     "type": "graph",
     "description": "The number of sets that have been replicated",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_set_docs_written{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "set_failed_cr_source",
     "type": "graph",
     "description": "The number of sets that have failed conflict resolution on the source due to optimistic replication\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_set_failed_cr_source{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "size_rep_queue",
     "type": "graph",
     "description": "Size of replication queue in bytes\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_size_rep_queue{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "throttle_latency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(xdcr_throttle_latency{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "wtavg_docs_latency",
     "type": "graph",
     "description": "Weighted average latency for sending replicated changes to target cluster\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(xdcr_wtavg_docs_latency{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "wtavg_meta_latency",
     "type": "graph",
     "description": "Weighted average time for requesting document metadata. XDCR uses this for conflict resolution prior to sending the document into the replication queue",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 45 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(xdcr_wtavg_meta_latency{type=\"xdcr\", cluster=~\"$cluster\", replication=~\"$replication\"})",
       "legendFormat": "docs"
      }
     ]
    }
   ]
  }
 ]
}