{
 "title": "Couchbase Cluster(s) Overview",
 "tags": [
  "Couchbase",
  "Cluster",
  "Buckets",
  "Index",
  "Query"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{type=\"bucket\"}"
   }
  ]
 },
 "panels": [
  { "title": "Bucket Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sets / sec",
   "type": "graph",
   "description": "Number of writes (set operations) per second to this bucket (measured from cmd_set)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(data_cmd_set{type=\"bucket\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Gets/sec",
   "type": "graph",
   "description": "Number of reads (get operations) per second from this bucket (measured from cmd_get)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(data_cmd_get{type=\"bucket\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Cache Miss Ratio",
   "type": "graph",
   "description": "Percentage of reads per second to this bucket from disk as opposed to RAM",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_cache_miss_rate{type=\"bucket\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "Memory used as measured from mem_used (in GB)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum(data_mem_used{type=\"bucket\", cluster=~\"$cluster\"}/1024/1024/1024) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Current Items",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(data_curr_items{type=\"bucket\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "CAS Ops/sec",
   "type": "graph",
   "description": "Number of operations with a CAS id per second for this bucket (measured from cas_hits)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(data_cas_hits{type=\"bucket\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "CPU Utilization Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg (data_cpu_utilization_rate{type=\"bucket\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Disk Write Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(data_disk_write_queue{type=\"bucket\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Disk Write Failures",
   "type": "graph",
   "description": "Number of disk read failures (measured from ep_data_read_failed)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_data_write_failed{type=\"bucket\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Temp OOM / sec",
   "type": "graph",
   "description": "Number of back-offs sent per second to client SDKs due to \"  \"\\\"out of memory\\\" situations from this bucket (measured from ep_tmp_oom_errors)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_tmp_oom_errors{type=\"bucket\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Disk Creates / sec",
   "type": "graph",
   "description": "Number of new items created on disk per second for this bucket \"\n                                       \"(measured from vb_active_ops_create + vb_replica_ops_create \"\n                                       \"+ vb_pending_ops_create",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_ops_create{type=\"bucket\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Disk Read Failures",
   "type": "graph",
   "description": "Number of disk read failures (measured from ep_data_read_failed)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_data_read_failed{type=\"bucket\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "N1QL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "N1QL Queries/sec",
   "type": "graph",
   "description": "Number of N1QL requests processed per second",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(query_requests{type=\"query\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "N1QL errors/sec",
   "type": "graph",
   "description": "Number of N1QL errors per second",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(query_errors{type=\"query\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "N1QL queued requests/sec",
   "type": "graph",
   "description": "Number of N1QL requests processed per second",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(query_queued_requests{type=\"query\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "N1QL Avg. Request Time",
   "type": "graph",
   "description": "Average N1QL Response Time",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(query_avg_req_time{type=\"query\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "N1QL Avg. Service Time",
   "type": "graph",
   "description": "Average Service Time for N1QL Queries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "ms", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(query_avg_svc_time{type=\"query\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "N1QL Avg. Response Size",
   "type": "graph",
   "description": "Avg. Size of N1QL Response",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "avg(query_avg_response_size{type=\"query\", cluster=~\"$cluster\"}/1024) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "N1QL Queries >500ms",
   "type": "graph",
   "description": "Number of N1QL requests that exceeded 500ms",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(query_requests_500ms{type=\"query\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "N1QL Queries >1000ms",
   "type": "graph",
   "description": "Number of N1QL requests > 1000ms",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(query_requests_1000ms{type=\"query\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "N1QL Queries >5000ms",
   "type": "graph",
   "description": "Number of N1QL requests >5000ms",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(query_requests_5000ms{type=\"query\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Total Mutations Remaining",
   "type": "graph",
   "description": "Number of documents pending to be indexed",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(index_num_docs_pending_queued{type=\"index\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Drain Rate Items/sec",
   "type": "graph",
   "description": "Number of documents indexed by the indexer per second",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(index_num_docs_indexed{type=\"index\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total Indexed Items",
   "type": "graph",
   "description": "Current total indexed document count",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(index_items_count{type=\"index\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Index Cache Miss Ratio",
   "type": "graph",
   "description": "Percentage of accesses to this index data\"\n                                    \"from disk as opposed to RAM (measured from\"\n                                    \"cache_misses * 100 / (cache_misses +\"\n                                    \"cache_hits))",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(index_cache_miss_ratio{type=\"index\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Index Memory Resident Percentage",
   "type": "graph",
   "description": "Percentage of index data resident in memory",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(index_resident_percent{type=\"index\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total memory consumed by the index storage",
   "type": "graph",
   "description": "Total memory consumed by the index storage",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum(index_memory_used{type=\"index\", cluster=~\"$cluster\"}/1024/1024/1024) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "items scanned/sec",
   "type": "graph",
   "description": "Number of index items scanned by the indexer per second",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(index_num_rows_returned{type=\"index\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Index Avg. Scan Latency",
   "type": "graph",
   "description": "Index  - Avg time to serve a scan request",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(index_avg_scan_latency{type=\"index\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Index Fragmentation Percentage",
   "type": "graph",
   "description": "percentage fragmentation of the index",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "percent", "label": "Percentage %" }
   ],
   "targets": [
    {
     "expr": "avg(index_frag_percent{type=\"index\", cluster=~\"$cluster\"}/2) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "XDCR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "XDCR Completeness Percentage",
   "type": "graph",
   "description": "Percentage of checked items out of all checked and to-be-replicated items",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(xdcr_percent_completeness{type=\"xdcr\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "XDCR Changes Left",
   "type": "graph",
   "description": "Number of changes left",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(xdcr_replication_changes_left{type=\"xdcr\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "XDCR Bandwidth Used",
   "type": "graph",
   "description": "Bandwidth used during replication, measured in bytes per second.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(xdcr_bandwidth_usage{type=\"xdcr\", cluster=~\"$cluster\"}/1024) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "XDCR # of Docs sent Optimistically ",
   "type": "graph",
   "description": "Number of documents sent optimistically",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(xdcr_docs_opt_repd{type=\"xdcr\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "XDCR # Docs Processed",
   "type": "graph",
   "description": "The number of documents processed",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(xdcr_docs_processed{type=\"xdcr\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "XDCR Docs Failed Conflict Resolution on Source",
   "type": "graph",
   "description": "The number of docs that have failed conflict resolution on the source due to optimistic replication",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(xdcr_docs_failed_cr_source{type=\"xdcr\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}