{
 "title": "Couchbase Indexes",
 "tags": [
  "Couchbase",
  "Indexes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{type=\"index\"}"
   },
   {
    "name": "index",
    "label": "Index",
    "query": "{type=\"index\", cluster=~\"$cluster\"}"
   }
  ]
 },
 "panels": [
  { "title": "Index Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "index_memory_quota",
   "type": "singlestat",
   "description": "The cluster wide memory quota.\n",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(index_memory_quota{type=\"index-service\", cluster=~\"$cluster\"})/1024/1024/1024"
    }
   ]
  },
  {
   "title": "index_memory_used",
   "type": "gauge",
   "description": "The amount of memory currently used by the indexing service.\n",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(index_memory_used{type=\"index-service\", cluster=~\"$cluster\"}/1024/1024/1024) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "index_remaining_ram",
   "type": "singlestat",
   "description": "The amount of memory remaining cluster wide",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(index_remaining_ram{type=\"index-service\", cluster=~\"$cluster\"})/1024/1024/1024"
    }
   ]
  },
  {
   "title": "index_remaining_ram",
   "type": "gauge",
   "description": "The amount of memory remaining.",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(index_remaining_ram{type=\"index-service\", cluster=~\"$cluster\"}/1024/1024/1024) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "index_ram_percent",
   "type": "singlestat",
   "description": "The percentage of index ram used\n",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(index_ram_percent{type=\"index-service\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "index_ram_percent",
   "type": "gauge",
   "description": "The percentage of index ram used\n",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(index_ram_percent{type=\"index-service\", cluster=~\"$cluster\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "All Indexes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "avg_item_size",
   "type": "graph",
   "description": "The average index entry size\n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(index_avg_item_size{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "avg_scan_latency",
   "type": "graph",
   "description": "The average latency when scanning the index\n",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(index_avg_scan_latency{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "cache_hits",
   "type": "graph",
   "description": "The number of in-memory hits to the index\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(index_cache_hits{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "hits"
    }
   ]
  },
  {
   "title": "cache_miss_ratio",
   "type": "graph",
   "description": "The ratio of misses to hits\n",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(index_cache_miss_ratio{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "cache_misses",
   "type": "graph",
   "description": "The number of in-memory misses to the index\n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(index_cache_misses{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "data_size",
   "type": "graph",
   "description": "The total data size of the index\n",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(index_data_size{type=\"index\", cluster=~\"$cluster\"}/1024/1024)",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "disk_overhead_estimate",
   "type": "graph",
   "description": "The size of stale data on disk due to fragmentation\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(index_disk_overhead_estimate{type=\"index\", cluster=~\"$cluster\"}/1024/1024)",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "disk_size",
   "type": "graph",
   "description": "The size of the index on disk\n",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(index_disk_size{type=\"index\", cluster=~\"$cluster\"}/1024/1024)",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "frag_percent",
   "type": "graph",
   "description": "The index fragmentation percentage\n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(index_frag_percent{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "fragmentation"
    }
   ]
  },
  {
   "title": "index_frag_percent",
   "type": "graph",
   "description": "The index fragmentation percentage\n",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(index_frag_percent{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "fragmentation"
    }
   ]
  },
  {
   "title": "index_resident_percent",
   "type": "graph",
   "description": "The percentage of the index that is memory resident\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(index_resident_percent{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "resident"
    }
   ]
  },
  {
   "title": "items_count",
   "type": "graph",
   "description": "The number of items in the index\n",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(index_items_count{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "items"
    }
   ]
  },
  {
   "title": "memory_used",
   "type": "graph",
   "description": "The amount of memory used by the index\n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(index_memory_used{type=\"index\", cluster=~\"$cluster\"}/1024/1024)",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "num_docs_indexed",
   "type": "graph",
   "description": "The number of items indexed since the last restart\n",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(index_num_docs_indexed{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "docs"
    }
   ]
  },
  {
   "title": "num_docs_pending+queued",
   "type": "graph",
   "description": "The number of documents that are pending or queued for indexing\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(index_num_docs_pending_queued{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "docs"
    }
   ]
  },
  {
   "title": "num_docs_queued",
   "type": "graph",
   "description": "The number of documents that are queued for indexing\n",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(index_num_docs_queued{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "docs"
    }
   ]
  },
  {
   "title": "num_requests",
   "type": "graph",
   "description": "The number of requests to the index\n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(index_num_requests{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "num_rows_returned",
   "type": "graph",
   "description": "The average number of rows returned by a scan\n",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(index_num_rows_returned{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "recs_in_mem",
   "type": "graph",
   "description": "The number of records in the index that are in memory\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(index_recs_in_mem{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "recs"
    }
   ]
  },
  {
   "title": "recs_on_disk",
   "type": "graph",
   "description": "The number of records not in memory\n",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(index_recs_on_disk{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "recs"
    }
   ]
  },
  {
   "title": "scan_bytes_read",
   "type": "graph",
   "description": "The average number of bytes read per scan\n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(index_scan_bytes_read{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "total_scan_duration",
   "type": "graph",
   "description": "The total time spent scanning",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(index_total_scan_duration{type=\"index\", cluster=~\"$cluster\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Index: $index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "repeat": "index",
   "collapsed": true,
   "panels": [
    {
     "title": "avg_item_size",
     "type": "graph",
     "description": "The average index entry size\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(index_avg_item_size{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "size"
      }
     ]
    },
    {
     "title": "avg_scan_latency",
     "type": "graph",
     "description": "The average latency when scanning the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(index_avg_scan_latency{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "latency"
      }
     ]
    },
    {
     "title": "cache_hits",
     "type": "graph",
     "description": "The number of in-memory hits to the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(index_cache_hits{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "hits"
      }
     ]
    },
    {
     "title": "cache_miss_ratio",
     "type": "graph",
     "description": "The ratio of misses to hits\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(index_cache_miss_ratio{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "misses"
      }
     ]
    },
    {
     "title": "cache_misses",
     "type": "graph",
     "description": "The number of in-memory misses to the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(index_cache_misses{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "misses"
      }
     ]
    },
    {
     "title": "data_size",
     "type": "graph",
     "description": "The total data size of the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "avg(index_data_size{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"}/1024/1024)",
       "legendFormat": "size"
      }
     ]
    },
    {
     "title": "disk_overhead_estimate",
     "type": "graph",
     "description": "The size of stale data on disk due to fragmentation\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "avg(index_disk_overhead_estimate{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"}/1024/1024)",
       "legendFormat": "size"
      }
     ]
    },
    {
     "title": "disk_size",
     "type": "graph",
     "description": "The size of the index on disk\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "avg(index_disk_size{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"}/1024/1024)",
       "legendFormat": "size"
      }
     ]
    },
    {
     "title": "frag_percent",
     "type": "graph",
     "description": "The index fragmentation percentage\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(index_frag_percent{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "fragmentation"
      }
     ]
    },
    {
     "title": "index_frag_percent",
     "type": "graph",
     "description": "The index fragmentation percentage\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(index_frag_percent{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "fragmentation"
      }
     ]
    },
    {
     "title": "index_resident_percent",
     "type": "graph",
     "description": "The percentage of the index that is memory resident\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(index_resident_percent{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "resident"
      }
     ]
    },
    {
     "title": "items_count",
     "type": "graph",
     "description": "The number of items in the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(index_items_count{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "items"
      }
     ]
    },
    {
     "title": "memory_used",
     "type": "graph",
     "description": "The amount of memory used by the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "avg(index_memory_used{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"}/1024/1024)",
       "legendFormat": "memory"
      }
     ]
    },
    {
     "title": "num_docs_indexed",
     "type": "graph",
     "description": "The number of items indexed since the last restart\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(index_num_docs_indexed{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "num_docs_pending+queued",
     "type": "graph",
     "description": "The number of documents that are pending or queued for indexing\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(index_num_docs_pending_queued{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "num_docs_queued",
     "type": "graph",
     "description": "The number of documents that are queued for indexing\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(index_num_docs_queued{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "docs"
      }
     ]
    },
    {
     "title": "num_requests",
     "type": "graph",
     "description": "The number of requests to the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(index_num_requests{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "num_rows_returned",
     "type": "graph",
     "description": "The average number of rows returned by a scan\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(index_num_rows_returned{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "rows"
      }
     ]
    },
    {
     "title": "recs_in_mem",
     "type": "graph",
     "description": "The number of records in the index that are in memory\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(index_recs_in_mem{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "recs"
      }
     ]
    },
    {
     "title": "recs_on_disk",
     "type": "graph",
     "description": "The number of records not in memory\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(index_recs_on_disk{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "recs"
      }
     ]
    },
    {
     "title": "scan_bytes_read",
     "type": "graph",
     "description": "The average number of bytes read per scan\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(index_scan_bytes_read{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "size"
      }
     ]
    },
    {
     "title": "total_scan_duration",
     "type": "graph",
     "description": "The total time spent scanning",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(index_total_scan_duration{type=\"index\", cluster=~\"$cluster\", index=~\"$index\"})",
       "legendFormat": "duration"
      }
     ]
    }
   ]
  }
 ]
}