{
 "title": "Couchbase vBuckets",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{type=\"bucket\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "{type=\"bucket\", cluster=\"$cluster\"}"
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\"}"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ep_vb_total",
   "type": "graph",
   "description": "Total number of vBuckets for this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "vBuckets" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_vb_total{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_avg_total_queue_age",
   "type": "graph",
   "description": "Average age in seconds of all items in the disk write queue for this bucket",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "avg(data_vb_avg_total_queue_age{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_total_queue_age",
   "type": "graph",
   "description": "Sum of disk queue item age in milliseconds.\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_total_queue_age{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  { "title": "Active vBuckets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "vb_active_eject",
   "type": "graph",
   "description": "Number of items per second being ejected to disk from \"active\"\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_active_eject{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_active_itm_memory",
   "type": "graph",
   "description": "Amount of active user data cached in RAM in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_active_itm_memory{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_active_meta_data_memory",
   "type": "graph",
   "description": "Amount of active item metadata consuming RAM in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_active_meta_data_memory{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_active_num",
   "type": "graph",
   "description": "Number of vBuckets in the \"active\" state for this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "vBuckets" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_active_num{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_active_num_non_resident",
   "type": "graph",
   "description": "Number of non-resident items.\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_active_num_non_resident{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_active_ops_create",
   "type": "graph",
   "description": "New items per second being inserted into \"active\" vBuckets in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_active_ops_create{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_active_ops_update",
   "type": "graph",
   "description": "Number of items updated on disk per second for this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_active_ops_update{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_active_queue_age",
   "type": "graph",
   "description": "Sum of disk queue item age in milliseconds for \"active\" vBuckets\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "avg(data_vb_active_queue_age{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_active_queue_drain",
   "type": "graph",
   "description": "Number of active items per second being written to disk in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_active_queue_drain{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_active_queue_fill",
   "type": "graph",
   "description": "Number of active items per second being put on the active item disk queue in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_active_queue_fill{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_active_queue_size",
   "type": "graph",
   "description": "Number of active items waiting to be written to disk in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_active_queue_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_active_resident_items_ratio",
   "type": "graph",
   "description": "Percentage of active items cached in RAM in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Percentage %" }
   ],
   "targets": [
    {
     "expr": "avg(data_vb_active_resident_items_ratio{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_avg_active_queue_age",
   "type": "graph",
   "description": "Average age in seconds of active items in the active item queue for this bucket",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "avg(data_vb_avg_active_queue_age{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  { "title": "Pending", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "vb_avg_pending_queue_age",
   "type": "graph",
   "description": "Average age in seconds of pending items in the pending item queue for this bucket and should be transient during rebalancing\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "avg(data_vb_avg_pending_queue_age{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_pending_curr_items",
   "type": "graph",
   "description": "Number of items in \"pending\" vBuckets in this bucket and should be transient during rebalancing\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_avg_pending_queue_age{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_pending_eject",
   "type": "graph",
   "description": "Number of items per second being ejected to disk from \"pending\" vBuckets in this bucket and should be transient during rebalancing\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Ejections" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_pending_eject{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_pending_itm_memory",
   "type": "graph",
   "description": "Amount of pending user data cached in RAM in this bucket and should be transient during rebalancing\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_pending_itm_memory{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_pending_meta_data_memory",
   "type": "graph",
   "description": "Amount of pending item metadata consuming RAM in this bucket and should be transient during rebalancing\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_pending_meta_data_memory{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_pending_num",
   "type": "graph",
   "description": "Number of vBuckets in the \"pending\" state for this bucket and should be transient during rebalancing",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "vBuckets" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_pending_num{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_pending_num_non_resident",
   "type": "graph",
   "description": "Number of non-resident items.\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_pending_num_non_resident{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_pending_ops_create",
   "type": "graph",
   "description": "New items per second being instead into \"pending\" vBuckets in this bucket and should be transient during rebalancing",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_pending_ops_create{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_pending_ops_update",
   "type": "graph",
   "description": "Number of items updated on disk per second for this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_pending_ops_update{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_pending_queue_age",
   "type": "graph",
   "description": "Sum of disk queue item age in milliseconds.\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "avg(data_vb_pending_queue_age{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_pending_queue_drain",
   "type": "graph",
   "description": "Number of pending items per second being written to disk in this bucket and should be transient during rebalancing\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_pending_queue_drain{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_pending_queue_fill",
   "type": "graph",
   "description": "Number of pending items per second being put on the pending item disk queue in this bucket and should be transient during rebalancing\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_pending_queue_fill{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_pending_queue_size",
   "type": "graph",
   "description": "Number of pending items waiting to be written to disk in this bucket and should be transient during rebalancing\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_pending_queue_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_pending_resident_items_ratio",
   "type": "graph",
   "description": "Percentage of items in pending state vbuckets cached in RAM in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "Percentage %" }
   ],
   "targets": [
    {
     "expr": "avg(data_vb_pending_resident_items_ratio{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  { "title": "Replica vBuckets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "ep_replica_ahead_exceptions",
   "type": "graph",
   "description": "Total number of ahead exceptions for all replica vBuckets\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Exceptions" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_replica_ahead_exceptions{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_replica_hlc_drift",
   "type": "graph",
   "description": "The sum of total_abs_drift for the node's active vBuckets\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Drifts" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_replica_hlc_drift{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_replica_hlc_drift_count",
   "type": "graph",
   "description": "The sum of total_abs_drift_count for the node's active vBuckets\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Drifts" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_replica_hlc_drift_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_avg_replica_queue_age",
   "type": "graph",
   "description": "Average age in seconds of replica items in the replica item queue for this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "avg(data_vb_avg_replica_queue_age{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_replica_curr_items",
   "type": "graph",
   "description": "Number of items in \"replica\" vBuckets in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_replica_curr_items{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_replica_eject",
   "type": "graph",
   "description": "Number of items per second being ejected to disk from \"replica\" vBuckets in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_replica_eject{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_replica_itm_memory",
   "type": "graph",
   "description": "Amount of replica user data cached in RAM in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_replica_itm_memory{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_replica_meta_data_memory",
   "type": "graph",
   "description": "Amount of replica item metadata consuming in RAM in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_replica_meta_data_memory{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_replica_num",
   "type": "graph",
   "description": "Number of vBuckets in the \"replica\" state for this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "short", "label": "vBuckets" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_replica_num{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_replica_num_non_resident",
   "type": "graph",
   "description": "Number of non-resident items.\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_replica_num_non_resident{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_replica_ops_create",
   "type": "graph",
   "description": "New items per second being inserted into \"replica\" vBuckets in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_replica_ops_create{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_replica_ops_update",
   "type": "graph",
   "description": "Number of items updated on disk per second for this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_replica_ops_update{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_replica_queue_age",
   "type": "graph",
   "description": "Sum of disk queue item age in milliseconds for \"replica\" vBuckets\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "avg(data_vb_replica_queue_age{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_replica_queue_drain",
   "type": "graph",
   "description": "Number of replica items per second being written to disk in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_replica_queue_drain{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_replica_queue_fill",
   "type": "graph",
   "description": "Number of replica items per second being put on the replica item disk queue in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_replica_queue_fill{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_replica_queue_size",
   "type": "graph",
   "description": "Number of replica items waiting to be written to disk in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_vb_replica_queue_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "vb_replica_resident_items_ratio",
   "type": "graph",
   "description": "Percentage of replica items cached in RAM in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "Percentage %" }
   ],
   "targets": [
    {
     "expr": "avg(data_vb_replica_resident_items_ratio{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}