{
 "title": "Couchbase Queries",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{type=\"query\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Queries / Sec",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(query_requests{type=\"query\", cluster=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Query Response Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(query_requests_250ms{type=\"query\", cluster=~\"$cluster\"})",
     "legendFormat": ">250ms"
    },
    {
     "expr": "sum(query_requests_500ms{type=\"query\", cluster=~\"$cluster\"})",
     "legendFormat": ">500ms"
    },
    {
     "expr": "sum(query_requests_1000ms{type=\"query\", cluster=~\"$cluster\"})",
     "legendFormat": ">1000ms"
    },
    {
     "expr": "sum(query_requests_5000ms{type=\"query\", cluster=~\"$cluster\"})",
     "legendFormat": ">5000ms"
    }
   ]
  },
  {
   "title": "Query Errors/Warnings",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(query_errors{type=\"query\", cluster=~\"$cluster\"})",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(query_warnings{type=\"query\", cluster=~\"$cluster\"})",
     "legendFormat": "warnings"
    },
    {
     "expr": "sum(query_invalid_requests{type=\"query\", cluster=~\"$cluster\"})",
     "legendFormat": "invalid"
    },
    {
     "expr": "sum(query_queued_requests{type=\"query\", cluster=~\"$cluster\"})",
     "legendFormat": "queued"
    }
   ]
  },
  {
   "title": "Query Results / Sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(query_result_count{type=\"query\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Response Size / Sec (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(query_result_size{type=\"query\", cluster=~\"$cluster\"}/1024/1024)"
    }
   ]
  },
  {
   "title": "Avg. Request Time (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(query_avg_req_time{type=\"query\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Avg. Service Time (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(query_avg_svc_time{type=\"query\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Slow Queries (By Response Time)",
   "type": "table-old",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(query_completed_request{type=\"completed-query\", cluster=~\"$cluster\"}) by (cluster,statement,fetches,query_selectivity_percent,result_size,result_count,scan_results)"
    }
   ]
  },
  {
   "title": "Slow Queries (By # of Fetches)",
   "type": "table-old",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg(query_completed_request_fetches{type=\"completed-request\", cluster=~\"$cluster\"}) by (cluster,statement)"
    }
   ]
  }
 ]
}