{
 "title": "Couchbase Buckets",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{type=\"bucket\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "{type=\"bucket\", cluster=\"$cluster\"}"
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\"}"
   }
  ]
 },
 "panels": [
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cas_hits",
   "type": "graph",
   "description": "Number of CAS operations per second for data that this bucket contains",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(data_cas_hits{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "cas_misses",
   "type": "graph",
   "description": "Number of CAS operations per second for data that this bucket does not contain",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(data_cas_misses{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "cmd_set",
   "type": "graph",
   "description": "Number of set operations serviced by this bucket",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(data_cmd_set{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "cmd_get",
   "type": "graph",
   "description": "Number of get operations serviced by this bucket",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(data_cmd_get{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "delete_hits",
   "type": "graph",
   "description": "Number of delete operations per second for this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Hits" }
   ],
   "targets": [
    {
     "expr": "sum(data_delete_hits{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "decr_misses",
   "type": "graph",
   "description": "Number of decr operations per second for data that this bucket does not contain\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Misses" }
   ],
   "targets": [
    {
     "expr": "sum(data_decr_misses{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "decr_hits",
   "type": "graph",
   "description": "Number of decrement operations per second for data that this bucket contains",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Hits" }
   ],
   "targets": [
    {
     "expr": "sum(data_decr_hits{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "delete_misses",
   "type": "graph",
   "description": "Number of delete operations per second for data that this bucket does",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Misses" }
   ],
   "targets": [
    {
     "expr": "sum(data_delete_misses{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_num_value_ejects",
   "type": "graph",
   "description": "Total number of items per second being ejected to disk in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Ejections" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_num_value_ejects{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_oom_errors",
   "type": "graph",
   "description": "Number of times unrecoverable OOMs happened while processing operations.\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_oom_errors{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_ops_create",
   "type": "graph",
   "description": "Total number of new items being inserted into this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Ops" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_ops_create{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_ops_update",
   "type": "graph",
   "description": "Number of items updated on disk per second for this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Ops" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_ops_update{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "get_hits",
   "type": "graph",
   "description": "Number of get operations per second for data that this bucket contains\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Hits" }
   ],
   "targets": [
    {
     "expr": "sum(data_get_hits{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "get_misses",
   "type": "graph",
   "description": "Number of get operations per second for data that this bucket does not contain\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Misses" }
   ],
   "targets": [
    {
     "expr": "sum(data_get_misses{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "hit_ratio",
   "type": "graph",
   "description": "Percentage of get requests served with data from this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "percent", "label": "Hit Percentage %" }
   ],
   "targets": [
    {
     "expr": "avg(data_hit_ratio{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "incr_hits",
   "type": "graph",
   "description": "Number of increment operations per second for data that this bucket contains\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Hits" }
   ],
   "targets": [
    {
     "expr": "sum(data_incr_hits{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "incr_misses",
   "type": "graph",
   "description": "Number of increment operations per second for data that this bucket does not contain\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Misses" }
   ],
   "targets": [
    {
     "expr": "sum(data_incr_misses{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "misses",
   "type": "graph",
   "description": "Total amount of operations per second for that that the bucket does not contain",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Misses" }
   ],
   "targets": [
    {
     "expr": "sum(data_misses{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ops",
   "type": "graph",
   "description": "Total amount of operations per second (including XDCR) to this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Ops" }
   ],
   "targets": [
    {
     "expr": "sum(data_ops{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "avg_active_timestamp_drift",
     "type": "graph",
     "description": "Average drift (in seconds) per mutation on active vBuckets",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "avg(data_avg_active_timestamp_drift{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "avg_bg_wait_time",
     "type": "graph",
     "description": "Average background fetch time in microseconds",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "ms", "label": "Milliseconds" }
     ],
     "targets": [
      {
       "expr": "sum(data_avg_bg_wait_time{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "bytes_written",
     "type": "graph",
     "description": "Number of bytes per second sent from this bucket",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "decbytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "avg(data_bytes_written{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "avg_active_timestamp_drift",
     "type": "graph",
     "description": "Average drift (in seconds) per mutation on active vBuckets",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "avg(data_avg_active_timestamp_drift{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "avg_replica_timestamp_drift",
     "type": "graph",
     "description": "Average drift (in seconds) per mutation on replica vBuckets",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "avg(data_avg_replica_timestamp_drift{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "bg_wait_count",
     "type": "graph",
     "description": "Number of background fetch operations",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(data_bg_wait_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "bg_wait_total",
     "type": "graph",
     "description": "Background fetch time in microseconds",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "µs", "label": "microseconds" }
     ],
     "targets": [
      {
       "expr": "avg(data_bg_wait_total{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "couch_views_actual_disk_size",
     "type": "graph",
     "description": "The size of all active items in all the indexes for this bucket on disk",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "decmbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "sum(data_couch_views_actual_disk_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "couch_docs_fragmentation",
     "type": "graph",
     "description": "How much fragmented data there is to be compacted compared to real data for the data files in this bucket",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "percent", "label": "Percentage %" }
     ],
     "targets": [
      {
       "expr": "avg(data_couch_docs_fragmentation{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "cas_badval",
     "type": "graph",
     "description": "Number of CAS operations per second using an incorrect CAS ID for data that this bucket contains",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short", "label": "ops" }
     ],
     "targets": [
      {
       "expr": "avg(data_cas_badval{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "couch_views_fragmentation",
     "type": "graph",
     "description": "How much fragmented data there is to be compacted compared to real data for the view index files in this bucket",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 52 },
     "yaxes": [
      { "format": "percent", "label": "Percentage %" }
     ],
     "targets": [
      {
       "expr": "avg(data_couch_views_fragmentation{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "couch_views_data_size",
     "type": "graph",
     "description": "The size of active data on for all the view indexes in this bucket",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
     "yaxes": [
      { "format": "decmbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "sum(data_couch_views_data_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "couch_docs_data_size",
     "type": "graph",
     "description": "The size of active data in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "decgbytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "sum(data_couch_docs_data_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "curr_items",
     "type": "graph",
     "description": "Number of unique items in this bucket - only active items, not replica",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 57 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_curr_items{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "couch_views_ops",
     "type": "graph",
     "description": "All the view reads for all design documents including scatter gather.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 57 },
     "yaxes": [
      { "format": "short", "label": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(data_couch_views_ops{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "curr_connections",
     "type": "graph",
     "description": "Number of connections to this server including connections from external client SDKs, proxies, DCP requests and internal statistic gathering",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "sum(data_curr_connections{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_active_hlc_drift",
     "type": "graph",
     "description": "The sum of total_abs_drift for the nodes active vBuckets\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 62 },
     "yaxes": [
      { "format": "short", "label": "Drifts" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_active_hlc_drift{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "curr_items",
     "type": "graph",
     "description": "Number of unique items in this bucket - only active items, not replica",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 62 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_curr_items{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_active_ahead_exceptions",
     "type": "graph",
     "description": "Total number of ahead exceptions for all active vBuckets\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short", "label": "Exceptions" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_active_ahead_exceptions{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_cache_miss_rate",
     "type": "graph",
     "description": "Percentage of reads per second to this bucket from disk as opposed to RAM\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 67 },
     "yaxes": [
      { "format": "percent", "label": "Percentage %" }
     ],
     "targets": [
      {
       "expr": "avg(data_ep_cache_miss_rate{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_active_hlc_drift_count",
     "type": "graph",
     "description": "The sum of total_abs_drift_count for the nodes active vBuckets\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 67 },
     "yaxes": [
      { "format": "short", "label": "Drifts" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_active_hlc_drift_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_clock_cas_drift_threshold_exceeded",
     "type": "graph",
     "description": "Percentage of reads per second to this bucket from disk as opposed to RAM\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "short", "label": "Drifts Exceeded" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_clock_cas_drift_threshold_exceeded{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "ep_kv_size",
   "type": "graph",
   "description": "Total amount of user data cached in RAM in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decgbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_kv_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "mem_used",
   "type": "graph",
   "description": "Amount of Memory used\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "decgbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(data_mem_used{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_mem_high_wat",
   "type": "graph",
   "description": "High water mark for auto-evictions\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "decgbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_mem_high_wat{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_mem_low_wat",
   "type": "graph",
   "description": "Low water mark for auto-evictions\n",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decgbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_mem_low_wat{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_max_size",
   "type": "graph",
   "description": "The maximum amount of memory this bucket can use.\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "decgbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_max_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_num_non_resident",
   "type": "graph",
   "description": "The number of non-resident items.\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_num_non_resident{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_overhead",
   "type": "graph",
   "description": "Extra memory used by transient data like persistence queues, replication queues, checkpoints, etc.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_overhead{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_meta_data_memory",
   "type": "graph",
   "description": "Total amount of item metadata consuming RAM in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "decgbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_meta_data_memory{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_resident_items_rate",
   "type": "graph",
   "description": "Percentage of all items cached in RAM in this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "percent", "label": "Percentage %" }
   ],
   "targets": [
    {
     "expr": "avg(data_ep_resident_items_rate{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_tmp_oom_errors",
   "type": "graph",
   "description": "Number of back-offs sent per second to client SDKs due to \"out of memory\" situations from this bucket",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_tmp_oom_errors{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "ep_queue_size",
   "type": "graph",
   "description": "Number of items queued for storage.\n",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    {
     "expr": "sum(data_ep_queue_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "evictions",
   "type": "graph",
   "description": "Number of items per second evicted from this bucket\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "Evictions" }
   ],
   "targets": [
    {
     "expr": "sum(data_evictions{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "XDCR",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "ep_num_ops_del_meta",
     "type": "graph",
     "description": "Number of delete operations per second for this bucket as the target for XDCR\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short", "label": "Ops" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_num_ops_del_meta{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_num_ops_del_ret_meta",
     "type": "graph",
     "description": "Number of delRetMeta operations per second for this bucket as the target for XDCR.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "short", "label": "Ops" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_num_ops_del_ret_meta{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_num_ops_get_meta",
     "type": "graph",
     "description": "Number of metadata read operations per second for this bucket as the target for XDCR\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "short", "label": "Ops" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_num_ops_get_meta{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_num_ops_set_meta\t",
     "type": "graph",
     "description": "Number of set operations per second for this bucket as the target for XDCR\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short", "label": "Ops" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_num_ops_set_meta{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_num_ops_set_ret_meta\t\t",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 64 },
     "yaxes": [
      { "format": "short", "label": "Ops" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_num_ops_set_ret_meta{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "xdc_ops",
     "type": "graph",
     "description": "Incoming XDCR operations per second for this bucket",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 64 },
     "yaxes": [
      { "format": "short", "label": "Ops" }
     ],
     "targets": [
      {
       "expr": "sum(data_xdc_ops{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "ep_data_write_failed\t",
     "type": "graph",
     "description": "Number of disk write failures\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "Failures" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_data_write_failed{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "disk_commit_count",
     "type": "graph",
     "description": "Disk commits.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "Commits" }
     ],
     "targets": [
      {
       "expr": "sum(data_disk_commit_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "disk_update_count",
     "type": "graph",
     "description": "Disk updates.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "Updates" }
     ],
     "targets": [
      {
       "expr": "sum(data_disk_update_count{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_bg_fetched",
     "type": "graph",
     "description": "Number of reads per second from disk for this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short", "label": "Fetches" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_bg_fetched{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_diskqueue_fill",
     "type": "graph",
     "description": "Total number of items per second being put on the disk queue in this\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 65 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_diskqueue_fill{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_diskqueue_items",
     "type": "graph",
     "description": "Total number of items waiting to be written to disk in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 65 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_diskqueue_items{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "couch_total_disk_size",
     "type": "graph",
     "description": "The total size on disk of all data and view files for this bucket.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "decgbytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "sum(data_couch_total_disk_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "couch_docs_disk_size",
     "type": "graph",
     "description": "The size of active data in this bucket on disk\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 70 },
     "yaxes": [
      { "format": "decgbytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "sum(data_couch_docs_disk_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "disk_commit_total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 70 },
     "yaxes": [
      { "format": "short", "label": "Commits" }
     ],
     "targets": [
      {
       "expr": "avg(data_disk_commit_total{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_data_read_failed",
     "type": "graph",
     "description": "Number of disk read failures\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short", "label": "Failures" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_data_read_failed{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "couch_views_disk_size",
     "type": "graph",
     "description": "The size of active data on for all the view indexes in this bucket on disk",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 75 },
     "yaxes": [
      { "format": "decmbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "sum(data_couch_views_disk_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "couch_docs_actual_disk_size",
     "type": "graph",
     "description": "The size of all data files for this bucket, including the data itself, metadata and temporary files",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 75 },
     "yaxes": [
      { "format": "decgbytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "sum(data_couch_docs_actual_disk_size{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}/1024/1024/1024) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "avg_disk_commit_time",
     "type": "graph",
     "description": "Average disk commit time in seconds as from disk_update histogram of timings",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "s", "label": "seconds" }
     ],
     "targets": [
      {
       "expr": "avg(data_avg_disk_commit_time{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_item_commit_failed",
     "type": "graph",
     "description": "Number of times a transaction failed to commit due to storage errors.\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 80 },
     "yaxes": [
      { "format": "short", "label": "Failures" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_item_commit_failed{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "disk_write_queue",
     "type": "graph",
     "description": "Number of items waiting to be written to disk in this bucket",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 80 },
     "yaxes": [
      { "format": "short", "label": "Writes" }
     ],
     "targets": [
      {
       "expr": "sum(data_disk_write_queue{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "disk_update_total",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short", "label": "Updates" }
     ],
     "targets": [
      {
       "expr": "sum(data_disk_update_total{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_diskqueue_drain",
     "type": "graph",
     "description": "Total number of items per second being written to disk in this bucket\n",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 85 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_diskqueue_drain{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "avg_disk_update_time",
     "type": "graph",
     "description": "Average disk update time in microseconds as from disk_update histogram of timings",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 85 },
     "yaxes": [
      { "format": "µs", "label": "microseconds" }
     ],
     "targets": [
      {
       "expr": "avg(data_avg_disk_update_time{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "ep_flusher_todo",
     "type": "graph",
     "description": "Number of items currently being written.\n",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "short", "label": "Items" }
     ],
     "targets": [
      {
       "expr": "sum(data_ep_flusher_todo{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\", bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  }
 ]
}