{
 "title": "Couchbase Performance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "{type=\"bucket\"}"
   },
   {
    "name": "node",
    "query": "{type=\"bucket\", cluster=\"$cluster\"}"
   },
   {
    "name": "bucket",
    "query": "{type=\"bucket\", cluster=~\"$cluster\", node=~\"$node\"}"
   },
   {
    "name": "node_index",
    "query": "{type=\"index\", cluster=~\"$cluster\"}"
   },
   {
    "name": "index",
    "query": "{type=\"index\", cluster=~\"$cluster\", node=~\"$node_index\"}"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status $node",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "repeat": "node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "status {cluster=~\"$cluster\", node=~\"$node\", type=\"nodes\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "curr_connections $node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "repeat": "node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(curr_connections{bucket=~\"$bucket\", node=~\"$node\"})",
     "legendFormat": "{{"
    }
   ]
  },
  { "title": "Bucket Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "sets per sec",
   "type": "graph",
   "description": "Number of writes (set operations) per second to this bucket (measured from cmd_set)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cmd_set{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "gets per sec",
   "type": "graph",
   "description": "Number of reads (get operations) per second from this bucket (measured from cmd_get)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cmd_get{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "cache_miss_ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_cache_miss_rate{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "Memory used as measured from mem_used (in GB)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mem_used{bucket=~\"$bucket\", node=~\"$node\"}/1024/1024/1024) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "curr_items",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(curr_items{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CAS ops per sec",
   "type": "graph",
   "description": "Number of operations with a CAS id per second for this bucket (measured from cas_hits)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cas_hits{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "cpu_utilization_rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cpu_utilization_rate{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "disk_write_queue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(disk_write_queue{bucket=~\"$bucket\", node=~\"$node\"}) by (node)"
    }
   ]
  },
  {
   "title": "disk write failures",
   "type": "graph",
   "description": "Number of disk read failures (measured from ep_data_read_failed)",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_data_write_failed{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "index data size",
   "type": "graph",
   "description": "Actual data size consumed by the index",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cmd_set{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "disk creates per sec.",
   "type": "graph",
   "description": "Number of new items created on disk per second for this bucket \"\n                                       \"(measured from vb_active_ops_create + vb_replica_ops_create \"\n                                       \"+ vb_pending_ops_create",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_ops_create{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "disk read failures",
   "type": "graph",
   "description": "Number of disk read failures (measured from ep_data_read_failed)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_data_read_failed{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "temp OOM per sec",
   "type": "graph",
   "description": "Number of back-offs sent per second to client SDKs due to \"  \"\\\"out of memory\\\" situations from this bucket (measured from ep_tmp_oom_errors)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ep_tmp_oom_errors{bucket=~\"$bucket\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "N1QL queries/sec",
   "type": "graph",
   "description": "Number of N1QL requests processed per second",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(query_requests{node=~\"$node\"}) by (node)"
    }
   ]
  },
  { "title": "Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "total mutations remaining",
   "type": "graph",
   "description": "Number of documents pending to be indexed",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_docs_pending_queued{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "drain rate items/sec",
   "type": "graph",
   "description": "Number of documents indexed by the indexer per second",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_docs_indexed{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "total indexed items",
   "type": "graph",
   "description": "Current total indexed document count",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "items_count{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "index cache miss ratio",
   "type": "graph",
   "description": "Percentage of accesses to this index data\"\n                                    \"from disk as opposed to RAM (measured from\"\n                                    \"cache_misses * 100 / (cache_misses +\"\n                                    \"cache_hits))",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cache_miss_ratio{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Percentage of index data resident in memory",
   "type": "graph",
   "description": "Percentage of index data resident in memory",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "index_resident_percent{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Total memory consumed by the index storage",
   "type": "graph",
   "description": "Total memory consumed by the index storage",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "memory_used{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "items scanned/sec",
   "type": "graph",
   "description": "Number of index items scanned by the indexer per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_rows_returned{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "avg_scan_latency",
   "type": "graph",
   "description": "Index  - Avg time to serve a scan request",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_scan_latency{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "index_frag_percent",
   "type": "graph",
   "description": "percentage fragmentation of the index",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "index_frag_percent{index=~\"[[index]]\", node=~\"[[node_index]]\"}",
     "legendFormat": "{{index}}"
    }
   ]
  }
 ]
}