#! /usr/bin/python
'''This is the main script for the python exporter for exporting Couchbase
 RestAPI metrics to Prometheus format.'''

# pylint: disable=C0303, C0325, C1801

URL = ''
USER = ''
PASSWD = ''

# This is an autogenerated file. DO NOT EDIT BELOW THIS LINE!!!

from modules import *

def get_metrics(url='', user='', passwrd=''):
	cluster_values = cb_cluster._get_cluster(url, user, passwrd, [])
	metrics = cluster_values['metrics']
	index_buckets = cb_bucket._get_index_buckets(url, user, passwrd)
	buckets = cb_bucket._get_buckets(url, user, passwrd)

	return(metrics)

if __name__ == '__main__':
	print(get_metrics(URL, USER, PASSWD))
