# This is an autogenerated file. DO NOT EDIT!!!

from flask import Response, make_response, Request, request, session, stream_with_context
from application import application
import main
from modules.cb_utilities import *
from modules import *

@application.route('/metrics', methods=['GET'])
@application.route('/', methods=['GET', 'POST'])
def metrics():
	_value = main.get_metrics(
		application.config['CB_DATABASE'],
		application.config['CB_USERNAME'],
		application.config['CB_PASSWORD'])

	if application.config['CB_STREAMING']:
		def generate():
			for row in _value:
				yield(row + '\n')
		return Response(stream_with_context(generate()), mimetype='text/plain')
	else:
		metrics_str = '\n'
		metrics_str = metrics_str.join(_value)
		return Response(metrics_str, mimetype='text/plain')
